### ISSUE TITLE
搭建问题

### ISSUE THREAD

**Issue by nnmv** [phcbest/mgddaka.autowork#2]
大佬 问一个特别小白的问题  这个上传服务器 后续的搭建怎么进行呀...小白一个  也是被蘑菇丁打卡 烦的烦死了

**Comment by phcbest** [comment]
数据库脚本执行一下，然后跑一下springboot的源码，之后再跑一下前端就行

**Comment by nnmv** [comment]
大佬 留个联系方式呗......emmmmm
